name: CI/CD Docker Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t n3dhir/hello-word-app:${{ github.sha }} .
          docker tag n3dhir/hello-word-app:${{ github.sha }} n3dhir/hello-word-app:latest

      - name: Push Docker image
        run: |
          docker push n3dhir/hello-word-app:${{ github.sha }}
          docker push n3dhir/hello-word-app:latest
